### ISSUE TITLE
function credit_invoice_output is missing after update to WHMCS 7.5...

### ISSUE THREAD

**Issue by xNUTx** [Onlineforce/whmcs-credit-invoice#2]
Exception: No such action in /path/to/wwwroot/modules/whmcs-credit-invoice/credit_invoice/credit_invoice.php:55
Stack trace:
#0 /path/to/wwwroot/modules/whmcs-credit-invoice/credit_invoice/credit_invoice.php(49): no_route_error()
#1 /path/to/wwwroot/iuadmin/addonmodules.php(0): credit_invoice_output(Array)
#2 {main}

**Comment by alexanderzinolidis** [comment]
Thanks @xNUTx, I will take a look at this as soon as possible.

**Comment by xNUTx** [comment]
@alexanderzinolidis if you give me some pointers I could try to find a fix myself, I'm no dummy but I am quite new to WHMCS' api/addon system.

I hope you can fix it easily, we actually use that module quite often.

**Comment by alexanderzinolidis** [comment]
@xNUTx What triggers the error? When you click the "credit invoice" button on the invoice view?

I just tried the module on WHMCS 7.5 with PHP 7.2.4 and it works alright.

Happy to hear that the module is of use to you, it's **bizarre** that WHMCS still has no credit note functionality.

**Comment by alexanderzinolidis** [comment]
@xNUTx I just pushed version 1.2 which hopefully fixes the issues you are seeing. I found some bad regex that might have been the cause. Let me know if you still see the issue.

**Comment by xNUTx** [comment]
Funny, I don't know if you ever got my messages, I tried replying by email yesterday. We will update today (in fact, it's why I am on github now). Will let you know how it fares.

**Comment by xNUTx** [comment]
This update fixed the issue, the module is working fine again :+1:
